[project]
name = "ai-math-tutor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-openai>=0.3.30",
    "pydantic>=2.9.2",
    "python-dotenv>=1.1.1",
    "streamlit>=1.47.1",
]
